'use client';

import { ChevronDown, LoaderCircle, Save, ShieldCheck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
import { aiProfileDataSchema, createAiProfile, type AiPolicies, type AiProfile } from '@/modules/merchant-preferences/ai-profile';
import { merchantProfileSaveDestination, type MerchantProfileSurface } from '@/modules/settings/business-profile/routes';

type Mode = AiProfile['setupMode'];
const modes: Array<{ id: Mode; title: string; description: string; badge?: string }> = [
  { id: 'LISTINGPILOT_SAFE_AI', title: 'Safe AI', description: 'Use verified facts only, flag uncertainty, and require merchant review.', badge: 'Recommended' },
  { id: 'BALANCED_AI', title: 'Balanced AI', description: 'Improve clarity and flow while preserving strict factual safeguards.' },
  { id: 'CREATIVE_AI', title: 'Creative AI', description: 'Allow broader presentation variation without inventing product facts.' },
  { id: 'MANUAL', title: 'Configure Manually', description: 'Choose evidence, review, localization, regeneration, and safety policies.' },
];
const inputClass = 'mt-1.5 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white';
function Select<T extends string>({ label, value, options, onChange }: { label: string; value: T; options: readonly T[]; onChange: (value: T) => void }) { return <label className="text-sm text-slate-300">{label}<select className={inputClass} value={value} onChange={(event) => onChange(event.target.value as T)}>{options.map((option) => <option key={option} value={option}>{option.replaceAll('_', ' ').toLocaleLowerCase().replace(/^\w/u, (letter) => letter.toLocaleUpperCase())}</option>)}</select></label>; }
function Input({ label, value, type = 'text', min, max, onChange }: { label: string; value: string | number; type?: 'text' | 'number'; min?: number; max?: number; onChange: (value: string) => void }) { return <label className="text-sm text-slate-300">{label}<input className={inputClass} value={value} type={type} min={min} max={max} onChange={(event) => onChange(event.target.value)} /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex min-h-11 items-center gap-3 rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-slate-300"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-violet-300" />{label}</label>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <details className="group rounded-2xl border border-white/10 bg-white/[0.035]"><summary className="flex cursor-pointer list-none items-center justify-between p-4 font-semibold text-white sm:p-5">{title}<ChevronDown className="h-4 w-4 text-slate-400 transition group-open:rotate-180" /></summary><div className="grid gap-4 border-t border-white/10 p-4 sm:grid-cols-2 sm:p-5">{children}</div></details>; }

export function MerchantAiProfileForm({ workspaceId, initial, surface = 'onboarding', canManage = true }: { workspaceId: string; initial: { version: number; data: AiProfile } | null; surface?: MerchantProfileSurface; canManage?: boolean }) {
  const router = useRouter(); const [selected, setSelected] = useState<Mode | null>(initial?.data.setupMode ?? null); const [profile, setProfile] = useState<AiProfile>(initial?.data ?? createAiProfile('LISTINGPILOT_SAFE_AI')); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const validation = useMemo(() => aiProfileDataSchema.safeParse(profile), [profile]);
  function choose(mode: Mode) { setSelected(mode); setProfile(createAiProfile(mode)); setError(null); }
  function patch<K extends keyof AiPolicies>(key: K, value: AiPolicies[K]) { setProfile((current) => ({ ...current, policies: { ...current.policies, [key]: value } })); }
  async function save() { if (!selected || !validation.success) { setError(validation.success ? 'Choose an AI setup mode.' : validation.error.issues[0]?.message ?? 'Review the AI Profile.'); return; } setSaving(true); setError(null); try { const response = await fetch('/api/onboarding/ai-profile', { method: 'PUT', headers: { accept: 'application/json', 'content-type': 'application/json' }, body: JSON.stringify({ workspaceId, expectedVersion: initial?.version ?? null, data: validation.data }) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? 'The AI Profile could not be saved.'); if (surface === 'settings') router.refresh(); else router.push(merchantProfileSaveDestination({ section: 'ai', surface, workspaceId })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The AI Profile could not be saved.'); } finally { setSaving(false); } }
  const policies = profile.policies;
  return <div>{!canManage ? <p className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/[0.07] p-4 text-sm text-amber-100">Only the workspace owner can edit the AI Profile.</p> : null}<fieldset disabled={!canManage} className="disabled:opacity-75"><h2 className="text-lg font-semibold text-white">How should ListingPilot use AI?</h2><p className="mt-2 text-sm leading-6 text-slate-400">Product Truth and your merchant rules always outrank AI suggestions.</p>
    <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{modes.map((mode) => <button key={mode.id} type="button" aria-pressed={selected === mode.id} onClick={() => choose(mode.id)} className={`min-w-0 rounded-2xl border p-5 text-left transition ${selected === mode.id ? 'border-violet-300/60 bg-violet-300/[0.10]' : 'border-white/10 bg-white/[0.035] hover:border-violet-300/30'}`}>{mode.badge ? <span className="rounded-full bg-emerald-300/10 px-2.5 py-1 text-xs font-semibold text-emerald-200">{mode.badge}</span> : null}<h3 className="mt-4 font-semibold text-white">{mode.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{mode.description}</p></button>)}</div>
    {selected ? <div className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-5 text-sm text-slate-300 sm:grid-cols-2"><p><strong className="text-white">Facts:</strong> Verified evidence remains authoritative</p><p><strong className="text-white">Missing data:</strong> Never guessed</p><p><strong className="text-white">Conflicts:</strong> Kept visible for review</p><p><strong className="text-white">Execution:</strong> AI generation remains disabled</p></div> : null}
    {selected === 'MANUAL' ? <div className="mt-6 space-y-3">
      <Panel title="Facts, creativity and review"><Select label="Factual strictness" value={policies.factualStrictness} options={['VERIFIED_ONLY', 'VERIFIED_AND_LIKELY_WITH_LABEL', 'ALLOW_MERCHANT_APPROVED_UNVERIFIED'] as const} onChange={(value) => patch('factualStrictness', value)} /><Select label="Presentation creativity" value={policies.creativity} options={['MINIMAL', 'LOW', 'MEDIUM'] as const} onChange={(value) => patch('creativity', value)} /><Select label="Uncertainty" value={policies.uncertainty} options={['OMIT_UNCERTAIN_FACTS', 'FLAG_FOR_REVIEW', 'INCLUDE_WITH_CLEAR_LABEL'] as const} onChange={(value) => patch('uncertainty', value)} /><Select label="Missing information" value={policies.missingInformation} options={['LEAVE_EMPTY', 'ADD_REVIEW_PLACEHOLDER', 'SUGGEST_EVIDENCE_NEEDED'] as const} onChange={(value) => patch('missingInformation', value)} /><Select label="Critical conflicts" value={policies.conflicts} options={['BLOCK_GENERATION_FOR_CRITICAL_CONFLICTS', 'GENERATE_WITH_CONFLICT_WARNING', 'ALLOW_MERCHANT_SELECTED_VALUE'] as const} onChange={(value) => patch('conflicts', value)} /><Select label="Tone variation" value={policies.toneVariation} options={['STRICT_PROFILE_TONE', 'ALLOW_MINOR_VARIATION', 'ALLOW_BROAD_VARIATION'] as const} onChange={(value) => patch('toneVariation', value)} /></Panel>
      <Panel title="Evidence requirements"><Select label="Minimum evidence" value={policies.evidence.minimumEvidenceLevel} options={['VERIFIED', 'LIKELY_WITH_REVIEW'] as const} onChange={(value) => patch('evidence', { ...policies.evidence, minimumEvidenceLevel: value })} /><Input label="Independent sources" type="number" min={1} max={10} value={policies.evidence.minimumIndependentSourceCount} onChange={(value) => patch('evidence', { ...policies.evidence, minimumIndependentSourceCount: Number(value) })} /><Select label="Source policy" value={policies.evidence.sourcePolicy} options={['REQUIRE_OFFICIAL_FOR_HIGH_RISK_FIELDS', 'PREFER_OFFICIAL', 'ALLOW_TRUSTED_RETAILER', 'ALLOW_MERCHANT_SOURCE'] as const} onChange={(value) => patch('evidence', { ...policies.evidence, sourcePolicy: value })} /><Select label="Missing provenance" value={policies.evidence.missingProvenanceCeiling} options={['OMIT', 'REVIEW_ONLY'] as const} onChange={(value) => patch('evidence', { ...policies.evidence, missingProvenanceCeiling: value })} /><Select label="Merchant overrides" value={policies.evidence.merchantOverrideTreatment} options={['REQUIRE_TRACEABLE_APPROVAL', 'ALLOW_APPROVED_WITH_WARNING'] as const} onChange={(value) => patch('evidence', { ...policies.evidence, merchantOverrideTreatment: value })} /><Select label="Stale evidence" value={policies.evidence.staleEvidenceTreatment} options={['REQUIRE_REVIEW', 'OMIT'] as const} onChange={(value) => patch('evidence', { ...policies.evidence, staleEvidenceTreatment: value })} /></Panel>
      <Panel title="Explanation and regeneration"><Select label="Explanation detail" value={policies.explanation.level} options={['MINIMAL', 'STANDARD', 'DETAILED'] as const} onChange={(value) => patch('explanation', { ...policies.explanation, level: value })} /><Select label="Regeneration" value={policies.regeneration.policy} options={['PRESERVE_APPROVED_CONTENT', 'REGENERATE_SELECTED_FIELDS_ONLY', 'REGENERATE_FULL_DRAFT'] as const} onChange={(value) => patch('regeneration', { ...policies.regeneration, policy: value })} /><Toggle label="Explain supporting sources" checked={policies.explanation.explainSource} onChange={(value) => patch('explanation', { ...policies.explanation, explainSource: value })} /><Toggle label="Explain remaining conflicts" checked={policies.explanation.explainConflicts} onChange={(value) => patch('explanation', { ...policies.explanation, explainConflicts: value })} /><Toggle label="Explain omitted fields" checked={policies.explanation.explainOmissions} onChange={(value) => patch('explanation', { ...policies.explanation, explainOmissions: value })} /><Toggle label="Explain review requirements" checked={policies.explanation.explainReviewRequirement} onChange={(value) => patch('explanation', { ...policies.explanation, explainReviewRequirement: value })} /><Toggle label="Explain profile influence" checked={policies.explanation.explainProfileInfluence} onChange={(value) => patch('explanation', { ...policies.explanation, explainProfileInfluence: value })} /></Panel>
      <Panel title="Language and localization"><Input label="Primary language (BCP-47)" value={policies.localization.primaryLanguage} onChange={(value) => patch('localization', { ...policies.localization, primaryLanguage: value })} /><Input label="Secondary language (optional)" value={policies.localization.secondaryLanguage ?? ''} onChange={(value) => patch('localization', { ...policies.localization, secondaryLanguage: value.trim() || null })} /><Input label="Locale" value={policies.localization.locale} onChange={(value) => patch('localization', { ...policies.localization, locale: value })} /><Input label="Market country code" value={policies.localization.market} onChange={(value) => patch('localization', { ...policies.localization, market: value.toUpperCase() })} /><Select label="Measurements" value={policies.localization.measurementSystem} options={['PRESERVE_SOURCE', 'METRIC', 'IMPERIAL'] as const} onChange={(value) => patch('localization', { ...policies.localization, measurementSystem: value })} /><Select label="Currency display" value={policies.localization.currencyDisplay} options={['PRESERVE_SOURCE', 'MERCHANT_CURRENCY'] as const} onChange={(value) => patch('localization', { ...policies.localization, currencyDisplay: value })} /><Input label="Currency code" value={policies.localization.currencyCode} onChange={(value) => patch('localization', { ...policies.localization, currencyCode: value.toUpperCase() })} /><Select label="Spelling" value={policies.localization.spellingVariant} options={['LOCALE_DEFAULT', 'AMERICAN_ENGLISH', 'BRITISH_ENGLISH'] as const} onChange={(value) => patch('localization', { ...policies.localization, spellingVariant: value })} /><Select label="Translation" value={policies.localization.translationPolicy} options={['DISABLED', 'MERCHANT_APPROVED_ONLY', 'ALLOW_DRAFT_TRANSLATIONS'] as const} onChange={(value) => patch('localization', { ...policies.localization, translationPolicy: value })} /></Panel>
      <Panel title="Human review thresholds">{(['ALWAYS_REVIEW', 'REVIEW_IF_UNCERTAIN', 'REVIEW_IF_HIGH_RISK', 'REVIEW_IF_CONFLICTED', 'REVIEW_IF_LOW_CONFIDENCE'] as const).map((threshold) => <Toggle key={threshold} label={threshold.replaceAll('_', ' ').toLocaleLowerCase()} checked={policies.humanReviewThresholds.includes(threshold)} onChange={(checked) => patch('humanReviewThresholds', checked ? [...policies.humanReviewThresholds, threshold] : policies.humanReviewThresholds.filter((value) => value !== threshold))} />)}</Panel>
      <Panel title="Bulk safeguards and processing policy"><Input label="Maximum review batch" type="number" min={1} max={100} value={policies.bulk.maximumReviewBatchSize} onChange={(value) => patch('bulk', { ...policies.bulk, maximumReviewBatchSize: Number(value) })} /><Select label="Quality tier" value={policies.modelPolicy.qualityTier} options={['ECONOMY', 'STANDARD', 'PREMIUM'] as const} onChange={(value) => patch('modelPolicy', { ...policies.modelPolicy, qualityTier: value })} /><Input label="Maximum retries" type="number" min={0} max={3} value={policies.modelPolicy.maxRetries} onChange={(value) => patch('modelPolicy', { ...policies.modelPolicy, maxRetries: Number(value) })} /><Input label="Maximum regenerations" type="number" min={0} max={10} value={policies.modelPolicy.maxRegenerations} onChange={(value) => patch('modelPolicy', { ...policies.modelPolicy, maxRegenerations: Number(value) })} /><Toggle label="Allow quality escalation" checked={policies.modelPolicy.allowEscalation} onChange={(value) => patch('modelPolicy', { ...policies.modelPolicy, allowEscalation: value })} /><Toggle label="Reuse verified analysis" checked={policies.modelPolicy.reuseVerifiedAnalysis} onChange={(value) => patch('modelPolicy', { ...policies.modelPolicy, reuseVerifiedAnalysis: value })} /></Panel>
      <div className="rounded-xl border border-emerald-300/15 bg-emerald-300/[0.05] p-4 text-sm leading-6 text-emerald-50">Non-negotiable factual prohibitions, high-risk review, approved-content preservation, per-product evidence, deterministic-first processing, and merchant approval remain locked on for every mode.</div>
    </div> : null}
    {error ? <p className="mt-4 text-sm text-rose-300" role="alert">{error}</p> : null}{selected ? <div className="mt-7 flex justify-end"><button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-violet-300 px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-45">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save AI Profile</button></div> : null}<p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-slate-500"><ShieldCheck className="h-3.5 w-3.5 shrink-0" />Saving this profile does not generate content, call a model, or change Shopify.</p></fieldset></div>;
}
