import { z } from 'zod';
import { immutableCopy } from '../../intelligence/domain/immutability.ts';
import { listingGenerationPlanFingerprint } from '../composition/plan-fingerprint.ts';
import { semanticListingGenerationPlanValue } from '../composition/generation-plan-composer.ts';
import { LISTING_GENERATION_COMPOSER_VERSION, LISTING_GENERATION_PLAN_SCHEMA_VERSION, LISTING_GENERATION_PLAN_VERSION, type ListingGenerationPlan } from '../domain/contracts.ts';
import { ListingGenerationError } from '../domain/errors.ts';

const parserSchema = z.object({ planId: z.string().min(1), schemaVersion: z.number().int(), planVersion: z.string(), composerVersion: z.string(), projectId: z.string().min(1), workspaceId: z.string().min(1), productId: z.string().min(1), listingStandardId: z.string().min(1), craftPlan: z.record(z.unknown()).nullable(), sourceFingerprint: z.string().min(1), productTruthFingerprint: z.string().min(1), productIntelligencePack: z.object({ id: z.string(), version: z.string(), categoryId: z.string() }).strict().nullable(), merchantProfileVersions: z.record(z.unknown()), generationStatus: z.enum(['READY', 'READY_WITH_WARNINGS', 'REVIEW_REQUIRED', 'BLOCKED', 'INSUFFICIENT_DATA', 'INVALID_CONFIGURATION']), generationEligibility: z.object({ status: z.string(), allowed: z.boolean(), blockers: z.array(z.unknown()), warnings: z.array(z.unknown()), reviewRequirements: z.array(z.unknown()), explanationCodes: z.array(z.string()) }).passthrough(), blockers: z.array(z.unknown()), warnings: z.array(z.unknown()), selectedFacts: z.array(z.object({ id: z.string(), fieldId: z.string(), productId: z.string(), selectionStatus: z.string() }).passthrough()), excludedFacts: z.array(z.unknown()), unresolvedFacts: z.array(z.unknown()), conflictedFacts: z.array(z.unknown()), titlePlan: z.object({ enabled: z.boolean(), selectedFactIds: z.array(z.string()) }).passthrough(), descriptionPlan: z.object({ enabled: z.boolean(), selectedFactIds: z.array(z.string()) }).passthrough(), featurePlan: z.object({ enabled: z.boolean(), selectedFactIds: z.array(z.string()) }).passthrough(), seoPlan: z.object({ enabled: z.boolean(), selectedFactIds: z.array(z.string()) }).passthrough(), catalogPlan: z.record(z.unknown()), metafieldPlan: z.record(z.unknown()), mediaPlan: z.record(z.unknown()), localizationPlan: z.record(z.unknown()), reviewRequirements: z.array(z.unknown()), lockedFields: z.array(z.unknown()), prohibitedOutputs: z.array(z.string()), aiPolicy: z.record(z.unknown()), publishingConstraints: z.record(z.unknown()), auditSummary: z.record(z.unknown()), planFingerprint: z.string().min(1), createdAt: z.string().datetime(), metadata: z.record(z.unknown()) }).strict();

export function parseListingGenerationPlan(value: unknown): ListingGenerationPlan {
  const parsed = parserSchema.safeParse(value); if (!parsed.success) throw new ListingGenerationError('INVALID_GENERATION_INPUT', 'The Listing Generation Plan structure is invalid.');
  if (parsed.data.schemaVersion !== LISTING_GENERATION_PLAN_SCHEMA_VERSION || parsed.data.planVersion !== LISTING_GENERATION_PLAN_VERSION || parsed.data.composerVersion !== LISTING_GENERATION_COMPOSER_VERSION) throw new ListingGenerationError('UNSUPPORTED_PLAN_VERSION', 'The Listing Generation Plan version is unsupported.');
  const plan = parsed.data as unknown as ListingGenerationPlan; if (listingGenerationPlanFingerprint(semanticListingGenerationPlanValue(plan)) !== plan.planFingerprint) throw new ListingGenerationError('INVALID_GENERATION_INPUT', 'The Listing Generation Plan fingerprint is invalid.');
  return immutableCopy(plan) as ListingGenerationPlan;
}
