import type { Metadata } from 'next';
import { CircleAlert, Sparkles } from 'lucide-react';
import { notFound } from 'next/navigation';
import { requireAuthenticatedUser } from '@/modules/auth/server/context';
import { MerchantCatalogProfileForm } from '@/modules/onboarding/catalog-profile/MerchantCatalogProfileForm';
import { resolveMerchantCatalogProfileAccess } from '@/modules/onboarding/catalog-profile/profile-context.server';
import { prismaMerchantCatalogProfileRepository } from '@/modules/onboarding/catalog-profile/prisma-profile-repository.server';
import { getMerchantCatalogProfile } from '@/modules/onboarding/catalog-profile/profile-service';
import {
  getTenantContextForUser,
  TenantAccessError,
} from '@/modules/tenancy/server/tenant-context';

export const metadata: Metadata = {
  title: 'Merchant Catalog Profile | ListingPilot AI',
};

interface MerchantCatalogProfilePageProps {
  searchParams: Promise<{
    workspaceId?: string | string[];
  }>;
}

export default async function MerchantCatalogProfilePage({
  searchParams,
}: MerchantCatalogProfilePageProps) {
  const user = await requireAuthenticatedUser();
  const parameters = await searchParams;
  const requestedWorkspaceId = typeof parameters.workspaceId === 'string'
    ? parameters.workspaceId
    : undefined;

  try {
    const initialTenant = await getTenantContextForUser(
      user.id,
      requestedWorkspaceId ? { workspaceId: requestedWorkspaceId } : {},
    );
    if (!initialTenant.workspace) notFound();
    const access = await resolveMerchantCatalogProfileAccess(
      user.id,
      initialTenant.workspace.id,
    );
    const profile = await getMerchantCatalogProfile(
      prismaMerchantCatalogProfileRepository,
      access.workspaceId,
    );

    return (
      <div className="mx-auto max-w-5xl pb-16 pt-10 sm:pt-14">
        <div className="max-w-3xl">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-amber-300">
            Catalog onboarding
          </p>
          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
            Merchant Catalog Profile
          </h1>
          <p className="mt-3 text-base leading-7 text-slate-400">
            Configure how your Shopify catalog is organized before generating your first listing.
          </p>
        </div>

        <div className="mt-7 flex items-start gap-4 rounded-2xl border border-amber-300/20 bg-gradient-to-r from-amber-300/[0.09] to-amber-300/[0.035] p-5 shadow-[0_18px_45px_rgba(0,0,0,0.16)]">
          <span className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-amber-300/15 text-amber-200">
            <Sparkles className="h-4 w-4" aria-hidden="true" />
          </span>
          <p className="text-sm leading-6 text-amber-50/90">
            <span className="font-semibold text-amber-100">Important:</span>{' '}
            The quality and consistency of every listing generated by ListingPilot
            depends on the information you provide here. Take a moment to configure
            your catalog carefully.
          </p>
        </div>

        <div className="mt-7 rounded-[2rem] border border-white/10 bg-[#081423]/95 p-5 shadow-[0_28px_80px_rgba(0,0,0,0.28)] sm:p-8">
          <MerchantCatalogProfileForm
            workspaceId={access.workspaceId}
            organizationId={access.organizationId}
            workspaceName={access.workspaceName}
            shopName={access.store?.shopName ?? null}
            shopDomain={access.store?.shopDomain ?? null}
            shopifyConnected={access.shopifyConnected}
            canManage={access.role === 'OWNER'}
            initialProfile={profile}
          />
        </div>

        <div className="mt-5 flex items-center justify-center gap-2 text-xs text-slate-600">
          <CircleAlert className="h-3.5 w-3.5" aria-hidden="true" />
          Your profile stays inside ListingPilot until you choose to publish later.
        </div>
      </div>
    );
  } catch (error) {
    if (error instanceof TenantAccessError) notFound();
    throw error;
  }
}
