import type { ListingCraftRulePack } from '../../domain/contracts.ts';

export const neovixCraftRulePack = Object.freeze({
  id: 'neovix',
  version: '1.2.0',
  displayName: 'NEOVIX Standard',
  description: 'A specification-first premium ecommerce methodology designed for structured, accurate and easy-to-scan product listings.',
  supportedListingStandardIds: Object.freeze(['NEOVIX']),
  principles: Object.freeze([
    'Accuracy before persuasion', 'Specifications before marketing', 'Verified claims only',
    'Important facts first', 'No repetitive feature stuffing', 'No unnecessary adjectives',
    'No invented customer benefits', 'Short and readable paragraphs', 'Technical clarity',
    'Premium but restrained tone', 'Category-aware feature priority', 'Model and variant identity preserved',
  ]),
  titleRules: Object.freeze({
    componentOrder: Object.freeze(['BRAND', 'MODEL', 'PRODUCT_TYPE', 'SIZE_OR_CAPACITY', 'PRIMARY_TECHNOLOGY', 'VERIFIED_DIFFERENTIATORS']),
    preferredCharacterRange: Object.freeze({ minimum: 45, maximum: 140 }),
    maximumDifferentiators: 3,
    identityComponents: Object.freeze(['BRAND', 'PRODUCT_TYPE', 'MODEL', 'SIZE_OR_CAPACITY']),
    removableComponentOrder: Object.freeze(['LOW_PRIORITY_DIFFERENTIATOR', 'SECONDARY_TECHNOLOGY', 'MARKETING_TERM', 'REDUNDANT_PRODUCT_WORDING']),
    allowCommas: false,
    preserveMerchantCapitalization: true,
  }),
  specificationRules: Object.freeze({
    defaultLabels: Object.freeze(['Model', 'Brand', 'Type', 'Capacity', 'Key Technologies', 'Programs / Functions', 'Control', 'Design', 'Finish', 'Version']),
    fieldGroups: Object.freeze([
      Object.freeze({ label: 'Model', fieldIds: Object.freeze(['model', 'model_number']), requiredByDefault: true }),
      Object.freeze({ label: 'Brand', fieldIds: Object.freeze(['brand']), requiredByDefault: true }),
      Object.freeze({ label: 'Type', fieldIds: Object.freeze(['product_type', 'type']), requiredByDefault: true }),
      Object.freeze({ label: 'Capacity', fieldIds: Object.freeze(['capacity', 'screen_size', 'room_coverage', 'dust_capacity', 'bin_capacity', 'water_tank_capacity']), requiredByDefault: false }),
      Object.freeze({ label: 'Key Technologies', fieldIds: Object.freeze(['technology', 'display_technology', 'resolution', 'processor', 'hdr', 'filtration', 'filter_type', 'additional_filters', 'water_treatment', 'air_projection', 'airflow', 'suction', 'power', 'sensors', 'particle_capture_claim']), requiredByDefault: false }),
      Object.freeze({ label: 'Programs / Functions', fieldIds: Object.freeze(['programs', 'functions', 'modes', 'operating_modes', 'smart_platform', 'gaming_features', 'streaming', 'oscillation', 'runtime', 'cleaner_heads', 'attachments', 'hair_compatibility']), requiredByDefault: false }),
      Object.freeze({ label: 'Control', fieldIds: Object.freeze(['control', 'controls', 'remote_control', 'app_control', 'voice_control', 'temperature_control', 'connectivity']), requiredByDefault: false }),
      Object.freeze({ label: 'Design', fieldIds: Object.freeze(['design', 'form_factor', 'dimensions']), requiredByDefault: false }),
      Object.freeze({ label: 'Finish', fieldIds: Object.freeze(['finish', 'color', 'colour', 'material']), requiredByDefault: false }),
      Object.freeze({ label: 'Version', fieldIds: Object.freeze(['version', 'series', 'model_year', 'generation']), requiredByDefault: false }),
    ]),
    exactVerifiedValues: true,
    omitUnavailableOptionalValues: true,
    maximumValueLength: 160,
    prohibitedTopics: Object.freeze(['pricing', 'inventory', 'delivery']),
  }),
  overviewRules: Object.freeze({
    preferredParagraphCount: 2,
    maximumParagraphCount: 2,
    identityFirst: true,
    specificationDumpingProhibited: true,
    benefitTranslation: 'SUPPORTED_ONLY',
    maximumCharacters: 700,
    prohibitedOpenings: Object.freeze(['bring', 'experience', 'transform', 'elevate', 'discover', 'perfect for', 'designed to revolutionize']),
  }),
  featureRules: Object.freeze({
    minimumCount: 8,
    maximumCount: 12,
    oneConceptPerFeature: true,
    technicalFirst: true,
    useProductIntelligencePriority: true,
    fillerProhibited: true,
  }),
  duplicationRules: Object.freeze({
    semanticComparison: true,
    requiredIdentityRepetitionAllowed: true,
    fullTitleRepetitionProhibited: true,
    semanticAliases: Object.freeze({
      television: Object.freeze(['tv']),
      '4k uhd': Object.freeze(['4k', 'uhd 4k', 'ultra hd']),
      'smart tv': Object.freeze(['smart television']),
      inch: Object.freeze(['inches', 'in']),
    }),
  }),
  wordingRules: Object.freeze({
    preferredVerbs: Object.freeze(['supports', 'includes', 'features', 'powered by', 'designed with', 'provides', 'allows']),
    prohibitedAbsoluteTerms: Object.freeze(['guarantees', 'eliminates', 'always', 'never', 'perfect', 'best', 'ultimate', 'unmatched', 'revolutionary', 'flawless', 'unbeatable', 'must-have']),
    prohibitedEmptyAdjectives: Object.freeze(['amazing', 'incredible', 'fantastic', 'stunning', 'awesome', 'superb']),
    preserveVerifiedTechnologyNames: true,
  }),
  identityRules: Object.freeze({
    protectedFields: Object.freeze(['brand', 'model', 'model_suffix', 'size', 'capacity', 'region', 'version', 'series', 'finish', 'condition']),
    preserveModelSuffix: true,
    preserveRegionalIdentity: true,
    preserveVariantFacts: true,
    inferCondition: false,
    vendorMayImplyBrand: false,
  }),
  categoryIntegration: Object.freeze({
    useProductIntelligenceFieldDefinitions: true,
    useProductIntelligenceFeaturePriorities: true,
    genericFallback: true,
  }),
  validationRules: Object.freeze([
    { id: 'neovix.title.identity-order', section: 'TITLE', severity: 'REVIEW', description: 'Verified identity components follow the NEOVIX order.' },
    { id: 'neovix.title.no-duplicates', section: 'TITLE', severity: 'WARNING', description: 'Semantic title components are not repeated.' },
    { id: 'neovix.specifications.exact-facts', section: 'SPECIFICATIONS', severity: 'ERROR', description: 'A structured fact block appears first and contains selected verified facts in NEOVIX label order.' },
    { id: 'neovix.overview.concise', section: 'OVERVIEW', severity: 'WARNING', description: 'The overview uses two concise paragraphs.' },
    { id: 'neovix.features.priority', section: 'FEATURES', severity: 'WARNING', description: 'Features use Product Intelligence priorities without filler.' },
    { id: 'neovix.duplication.semantic', section: 'CROSS_SECTION', severity: 'WARNING', description: 'Explanatory content is not repeated excessively.' },
    { id: 'neovix.wording.restrained', section: 'CROSS_SECTION', severity: 'REVIEW', description: 'Unsupported promotional language is prohibited.' },
    { id: 'neovix.identity.preserved', section: 'CROSS_SECTION', severity: 'ERROR', description: 'Model and variant identity are preserved.' },
  ]),
} satisfies ListingCraftRulePack);
