import { DeterministicHasher } from '../../intelligence/deterministic/services.ts';
import type { NormalizedProduct } from '../../intelligence/domain/types.ts';
import type { ProductTruthReport, TruthFinding, TruthResolutionStatus } from '../../intelligence/product-truth/types.ts';
import { televisionIntelligencePack, type ProductIntelligenceAnalysisResult, type ProductIntelligencePack } from '../../product-intelligence/index.ts';
import { createAiPolicyContext, createAiProfile, createListingProfileForStandard, createMerchantBusinessProfile, createMerchantPreferenceRegistry, createPublishingPolicyContext, createPublishingProfile, createSeoProfile, resolveEffectiveMerchantPreferences, stableMerchantPreferenceFingerprint, type CatalogPreferenceData, type MerchantBusinessProfileRecord, type MerchantPreferenceSectionRecord } from '../../merchant-preferences/index.ts';
import type { ListingGenerationInput, LockedGenerationField } from '../domain/contracts.ts';

const now = '2026-08-07T12:00:00.000Z';
const workspaceId = '00000000-0000-4000-8000-000000000001';
const projectId = '00000000-0000-4000-8000-000000000002';
const productId = 'product-1';
function section(sectionId: MerchantPreferenceSectionRecord['sectionId'], payload: unknown): MerchantPreferenceSectionRecord { return { id: `section-${sectionId}`, workspaceId, sectionId, schemaVersion: 1, version: 1, status: 'COMPLETE', validationStatus: 'VALID', source: 'MANUAL', payload, fingerprint: stableMerchantPreferenceFingerprint(payload), metadata: {}, completedAt: new Date(now), createdAt: new Date(now), updatedAt: new Date(now) }; }
function finding(fieldPath: string, value: string, status: TruthResolutionStatus = 'VERIFIED', options: Partial<TruthFinding> = {}): TruthFinding { const fingerprint = new DeterministicHasher().hash({ productId, fieldPath, value, status, variantId: options.variantId }); return { id: `finding-${fieldPath}-${options.variantId ?? 'product'}`, productId, ...(options.variantId ? { variantId: options.variantId } : {}), claimGroupId: `group-${fieldPath}`, fieldPath, claimLabel: fieldPath, importance: 'HIGH', status, ...(status !== 'UNRESOLVED' && status !== 'INSUFFICIENT_EVIDENCE' ? { selectedValue: value } : {}), candidateValues: [value], confidence: { value: status === 'VERIFIED' ? 0.95 : 0.65, level: status === 'VERIFIED' ? 'VERY_HIGH' : 'MEDIUM', strategyVersion: '1.0.0', factors: [] }, confidenceMeaning: 'RESOLUTION_STATUS', evidenceSummary: { evidenceCount: 2, independentSourceCount: 1, strongestAuthority: 'MANUFACTURER_STRUCTURED', missingProvenanceCount: 0 }, conflictSummary: { materiallySupportedCandidateCount: status === 'CONFLICTED' ? 2 : 1, conflictingEvidenceCount: status === 'CONFLICTED' ? 1 : 0, hasMaterialConflict: status === 'CONFLICTED' }, explanation: `${fieldPath} resolved as ${status}.`, reviewRequirement: status === 'CONFLICTED' ? 'BLOCKING' : status === 'LIKELY' ? 'REQUIRED' : 'NONE', associatedIssueIds: [], associatedRecommendationIds: [], deterministicFingerprint: fingerprint, metadata: {}, ...options }; }
export function truthFindings(): TruthFinding[] { return [finding('brand', 'Acme'), finding('model', 'X1000'), finding('product_type', 'Television'), finding('screen_size', '55'), finding('resolution', '4K UHD'), finding('display_technology', 'OLED'), finding('refresh_rate', '120 Hz'), finding('smart_platform', 'Example OS')]; }
function report(findings: readonly TruthFinding[]): ProductTruthReport { return { schemaVersion: '1.0.0', capabilityId: 'product-truth', capabilityVersion: '1.0.0', analysisScope: 'SINGLE_PRODUCT', productCount: 1, claimCount: findings.length, claimGroupCount: findings.length, resolvedCount: findings.length, verifiedCount: findings.filter(({ status }) => status === 'VERIFIED').length, likelyCount: findings.filter(({ status }) => status === 'LIKELY').length, conflictedCount: findings.filter(({ status }) => status === 'CONFLICTED').length, unresolvedCount: findings.filter(({ status }) => status === 'UNRESOLVED').length, insufficientEvidenceCount: findings.filter(({ status }) => status === 'INSUFFICIENT_EVIDENCE').length, merchantOverrideCount: findings.filter(({ status }) => status === 'MERCHANT_OVERRIDE').length, notApplicableCount: 0, findings, confidenceDistribution: {}, evidenceSourceDistribution: {}, resolutionStrategyStatistics: {}, warnings: [], deterministicFingerprint: new DeterministicHasher().hash(findings.map(({ deterministicFingerprint }) => deterministicFingerprint).sort()), createdAt: now }; }
function analysis(pack: ProductIntelligencePack | null): ProductIntelligenceAnalysisResult | null { return pack ? { productId, categoryDetection: { category: pack.identity.categoryId, matchedPackId: pack.identity.id, matchedPackVersion: pack.identity.version, confidence: 'HIGH', score: 100, evidence: [], negativeEvidence: [], competingCandidates: [], detectorVersion: '1.0.0', status: 'MATCHED' }, intelligencePack: { id: pack.identity.id, version: pack.identity.version }, categoryRequirements: { missingIdentityFields: [], missingCategoryFields: [], missingRecommendedFields: [] }, categoryValidationFindings: [] } : { productId, categoryDetection: { category: 'UNKNOWN', matchedPackId: null, matchedPackVersion: null, confidence: 'LOW', score: 0, evidence: [], negativeEvidence: [], competingCandidates: [], detectorVersion: '1.0.0', status: 'UNKNOWN' }, intelligencePack: null, categoryRequirements: { missingIdentityFields: [], missingCategoryFields: [], missingRecommendedFields: [] }, categoryValidationFindings: [] }; }
function preferences(listingStandard: 'NEOVIX' | 'MARKETPLACE' | 'MINIMAL' = 'NEOVIX') { const catalog: CatalogPreferenceData = { setupMode: 'MANUAL', collections: ['Featured'], productTypes: ['Television'], vendors: ['Northwind'] }; const publishing = createPublishingProfile('MANUAL'); publishing.policies.brandVendor.policy = 'PRESERVE_VENDOR'; const listing = createListingProfileForStandard(listingStandard); listing.configurationStatus = 'CONFIGURED'; const record: MerchantBusinessProfileRecord = { id: 'profile-1', workspaceId, version: 1, status: 'COMPLETE', lastCompletedSectionId: 'ai', fingerprint: 'a'.repeat(64), metadata: {}, createdAt: new Date(now), updatedAt: new Date(now), sections: [section('catalog', catalog), section('listing', listing), section('seo', createSeoProfile('LISTINGPILOT_STANDARD')), section('publishing', publishing), section('ai', createAiProfile('LISTINGPILOT_SAFE_AI'))] }; const registry = createMerchantPreferenceRegistry(); return resolveEffectiveMerchantPreferences(workspaceId, createMerchantBusinessProfile(record, registry), registry); }
function product(): NormalizedProduct { return { id: productId, sourceReferences: [{ sourceType: 'MANUAL', label: 'Fixture', retrievedAt: now, metadata: {} }], title: 'Acme X1000 Television', description: 'Existing verified product description.', vendor: 'Northwind', productType: 'Television', categories: ['Electronics'], tags: ['Featured'], status: 'DRAFT', specifications: [], variants: [{ id: 'variant-55', sourceReferences: [], title: '55 inch', options: { Size: '55' }, attributes: {}, inventoryAttributes: {}, measurementMetadata: {}, evidenceIds: [] }], media: [{ id: 'image-1', type: 'IMAGE', url: 'https://example.com/image.jpg', position: 1, evidenceIds: [] }], seo: { title: 'Acme X1000', description: 'Existing SEO', handle: 'acme-x1000', evidenceIds: [] }, attributes: {}, evidenceIds: [], createdAt: now, updatedAt: now, extensions: {} }; }

export function generationInput(options: { findings?: readonly TruthFinding[]; pack?: ProductIntelligencePack | null; listingStandard?: 'NEOVIX' | 'MARKETPLACE' | 'MINIMAL'; lockedFields?: readonly LockedGenerationField[]; mutate?: (input: ListingGenerationInput) => void } = {}): ListingGenerationInput {
  const pack = options.pack === undefined ? televisionIntelligencePack : options.pack; const effective = preferences(options.listingStandard); const input: ListingGenerationInput = { project: { id: projectId, workspaceId, productId, version: 1, expectedVersion: 1, status: 'DRAFT', currentListing: { title: 'Locked merchant title', description: 'Existing description' }, currentSeo: { title: 'Existing SEO', description: 'Existing description', handle: 'acme-x1000' }, shopifyProductId: 'gid://shopify/Product/1' }, product: product(), productTruth: report(options.findings ?? truthFindings()), productIntelligence: { analysis: analysis(pack), pack }, merchantPreferences: structuredClone(effective), aiPolicy: structuredClone(createAiPolicyContext(effective.ai)), publishingPolicy: structuredClone(createPublishingPolicyContext(effective.publishing)), aiDetectiveFindings: [], recommendations: [], lockedFields: options.lockedFields ?? [], sourceFingerprint: 'source-fingerprint', snapshotCreatedAt: now, profileVersions: { catalog: { schemaVersion: 1, version: 1, fingerprint: effective.catalog.fingerprint }, listing: { schemaVersion: 1, version: 1, fingerprint: effective.listing.fingerprint }, seo: { schemaVersion: 1, version: 1, fingerprint: effective.seo.fingerprint }, publishing: { schemaVersion: 1, version: 1, fingerprint: effective.publishing.fingerprint }, ai: { schemaVersion: 1, version: 1, fingerprint: effective.ai.fingerprint } } };
  options.mutate?.(input); return input;
}
export { finding, now, productId, projectId, workspaceId };
