'use client';

import { ChevronDown, LoaderCircle, Save, ShieldCheck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
import { createSeoProfile, searchIntentSchema, seoProfileDataSchema, type SeoProfile, type SeoRules } from '@/modules/merchant-preferences/seo-profile';
import { merchantProfileSaveDestination, type MerchantProfileSurface } from '@/modules/settings/business-profile/routes';

type Mode = SeoProfile['setupMode'];
const modes: Array<{ id: Mode; title: string; description: string; badge?: string }> = [
  { id: 'LISTINGPILOT_STANDARD', title: 'ListingPilot SEO Standard', description: 'Use professional ecommerce SEO defaults and customize them later.', badge: 'Recommended' },
  { id: 'REVIEW_EXISTING_SEO', title: 'Review My Existing SEO', description: 'Inspect Shopify SEO patterns as reference before applying ListingPilot standards.' },
  { id: 'MANUAL', title: 'Configure Manually', description: 'Define SEO preferences from safe technical defaults.' },
];
const inputClass = 'mt-1.5 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white';
function Check({ label, checked, onChange, disabled = false }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { return <label className="flex min-h-9 items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 rounded border-white/20 bg-slate-950 text-amber-300" />{label}</label>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <details className="group rounded-2xl border border-white/10 bg-white/[0.035]"><summary className="flex cursor-pointer list-none items-center justify-between p-4 font-semibold text-white sm:p-5">{title}<ChevronDown className="h-4 w-4 text-slate-400 transition group-open:rotate-180" /></summary><div className="grid gap-4 border-t border-white/10 p-4 sm:grid-cols-2 sm:p-5">{children}</div></details>; }

export function MerchantSeoProfileForm({ workspaceId, initial, surface = 'onboarding', canManage = true }: { workspaceId: string; initial: { version: number; data: SeoProfile } | null; surface?: MerchantProfileSurface; canManage?: boolean }) {
  const router = useRouter();
  const [selected, setSelected] = useState<Mode | null>(initial?.data.setupMode ?? null);
  const [profile, setProfile] = useState<SeoProfile>(initial?.data ?? createSeoProfile('LISTINGPILOT_STANDARD'));
  const [editorVisible, setEditorVisible] = useState(Boolean(initial));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const validation = useMemo(() => seoProfileDataSchema.safeParse(profile), [profile]);
  function choose(mode: Mode) { setSelected(mode); setProfile(createSeoProfile(mode)); setEditorVisible(false); setError(null); }
  function patch<K extends keyof SeoRules>(key: K, value: SeoRules[K]) { setProfile((current) => ({ ...current, rules: { ...current.rules, [key]: value } })); }
  async function save() {
    if (!selected || !validation.success) { setError(validation.success ? 'Choose an SEO setup mode.' : validation.error.issues[0]?.message ?? 'Review the SEO Profile.'); return; }
    setSaving(true); setError(null);
    try {
      const response = await fetch('/api/onboarding/seo-profile', { method: 'PUT', headers: { accept: 'application/json', 'content-type': 'application/json' }, body: JSON.stringify({ workspaceId, expectedVersion: initial?.version ?? null, data: validation.data }) });
      const body = await response.json() as { error?: { message?: string } };
      if (!response.ok) throw new Error(body.error?.message ?? 'The SEO Profile could not be saved.');
      if (surface === 'settings') router.refresh();
      else router.push(merchantProfileSaveDestination({ section: 'seo', surface, workspaceId }));
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'The SEO Profile could not be saved.'); } finally { setSaving(false); }
  }
  const r = profile.rules;
  return <div>
    {!canManage ? <p className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/[0.07] p-4 text-sm text-amber-100">Only the workspace owner can edit the SEO Profile.</p> : null}
    <fieldset disabled={!canManage} className="disabled:opacity-75">
    <h2 className="text-lg font-semibold text-white">How would you like to configure SEO?</h2>
    <div className="mt-4 grid gap-4 lg:grid-cols-3">{modes.map((mode) => <button key={mode.id} type="button" aria-pressed={selected === mode.id} onClick={() => choose(mode.id)} className={`rounded-2xl border p-5 text-left transition ${selected === mode.id ? 'border-amber-300/60 bg-amber-300/[0.10]' : 'border-white/10 bg-white/[0.035] hover:border-amber-300/30'}`}>{mode.badge ? <span className="rounded-full bg-emerald-300/10 px-2.5 py-1 text-xs font-semibold text-emerald-200">{mode.badge}</span> : null}<h3 className="mt-4 font-semibold text-white">{mode.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{mode.description}</p></button>)}</div>
    {selected === 'REVIEW_EXISTING_SEO' ? <div className="mt-5 rounded-xl border border-sky-300/20 bg-sky-300/[0.07] p-4 text-sm leading-6 text-sky-100">Your existing Shopify SEO will be reviewed for patterns and problems. It will not be treated as automatically correct. Analysis is recorded as pending while ListingPilot safety defaults remain approved.</div> : null}
    {selected && !editorVisible ? <div className="mt-6 flex justify-end"><button type="button" onClick={() => setEditorVisible(true)} className="rounded-xl bg-amber-300 px-5 py-3 text-sm font-semibold text-slate-950">Continue</button></div> : null}
    {selected && editorVisible ? <div className="mt-7 space-y-3">
      <Panel title="SEO Titles"><label className="text-sm text-slate-300">Brand placement<select className={inputClass} value={r.title.brandPlacement} onChange={(e) => patch('title', { ...r.title, brandPlacement: e.target.value as SeoRules['title']['brandPlacement'] })}>{['FIRST','LAST','OMIT_WHEN_UNNECESSARY'].map(v => <option key={v}>{v}</option>)}</select></label><label className="text-sm text-slate-300">Separator<select className={inputClass} value={r.title.separator} onChange={(e) => patch('title', { ...r.title, separator: e.target.value as SeoRules['title']['separator'] })}>{['PIPE','DASH','EN_DASH','MIDDLE_DOT','NONE'].map(v => <option key={v}>{v}</option>)}</select></label><label className="text-sm text-slate-300">Target minimum<input className={inputClass} type="number" value={r.title.targetRange.minimum} onChange={(e) => patch('title', { ...r.title, targetRange: { ...r.title.targetRange, minimum: Number(e.target.value) } })} /></label><label className="text-sm text-slate-300">Target maximum<input className={inputClass} type="number" value={r.title.targetRange.maximum} onChange={(e) => patch('title', { ...r.title, targetRange: { ...r.title.targetRange, maximum: Number(e.target.value) } })} /></label><Check label="Include model number" checked={r.title.includeModelNumber} onChange={(v) => patch('title', { ...r.title, includeModelNumber: v })} /><Check label="Prevent duplicate titles" checked={r.title.preventDuplicates} onChange={(v) => patch('title', { ...r.title, preventDuplicates: v })} /></Panel>
      <Panel title="Meta Descriptions"><label className="text-sm text-slate-300">Tone<select className={inputClass} value={r.metaDescription.tone} onChange={(e) => patch('metaDescription', { ...r.metaDescription, tone: e.target.value as SeoRules['metaDescription']['tone'] })}>{['CLEAR','TECHNICAL','PREMIUM','CONVERSION_FOCUSED','MINIMAL'].map(v => <option key={v}>{v}</option>)}</select></label><label className="text-sm text-slate-300">CTA policy<select className={inputClass} value={r.metaDescription.ctaPolicy} onChange={(e) => patch('metaDescription', { ...r.metaDescription, ctaPolicy: e.target.value as SeoRules['metaDescription']['ctaPolicy'] })}>{['NONE','SOFT','DIRECT'].map(v => <option key={v}>{v}</option>)}</select></label><Check label="Product identity first" checked={r.metaDescription.productIdentityFirst} onChange={(v) => patch('metaDescription', { ...r.metaDescription, productIdentityFirst: v })} /><Check label="Prevent duplicates" checked={r.metaDescription.preventDuplicates} onChange={(v) => patch('metaDescription', { ...r.metaDescription, preventDuplicates: v })} /></Panel>
      <Panel title="URL Handles"><label className="text-sm text-slate-300">Existing handle policy<select className={inputClass} value={r.urlHandle.existingHandlePolicy} onChange={(e) => patch('urlHandle', { ...r.urlHandle, existingHandlePolicy: e.target.value as SeoRules['urlHandle']['existingHandlePolicy'] })}>{['PRESERVE_EXISTING','SUGGEST_IMPROVEMENT','ALLOW_REPLACEMENT_WITH_CONFIRMATION'].map(v => <option key={v}>{v}</option>)}</select></label><label className="text-sm text-slate-300">Maximum words<input className={inputClass} type="number" value={r.urlHandle.maximumWordCount} onChange={(e) => patch('urlHandle', { ...r.urlHandle, maximumWordCount: Number(e.target.value) })} /></label><Check label="Lowercase" checked={r.urlHandle.enforceLowercase} onChange={() => {}} disabled /><Check label="Redirect required for replacement" checked={r.urlHandle.redirectRequiredForReplacement} onChange={() => {}} disabled /></Panel>
      <Panel title="Search Intent & Keywords"><label className="text-sm text-slate-300 sm:col-span-2">Ordered priorities (comma separated)<input className={inputClass} value={r.searchIntent.priorities.join(', ')} onChange={(e) => { const values = e.target.value.split(',').map(v => v.trim()).filter(Boolean); const parsed = searchIntentSchema.array().safeParse(values); if (parsed.success) patch('searchIntent', { priorities: parsed.data }); }} /></label><label className="text-sm text-slate-300">Keyword repetition threshold<input className={inputClass} type="number" step="0.1" value={r.keywords.repetitionThreshold} onChange={(e) => patch('keywords', { ...r.keywords, repetitionThreshold: Number(e.target.value) })} /></label><Check label="Keyword stuffing protection" checked={r.keywords.preventKeywordStuffing} onChange={() => {}} disabled /></Panel>
      <Panel title="Branding"><label className="text-sm text-slate-300">Preferred store display name<input className={inputClass} value={r.branding.preferredStoreDisplayName} onChange={(e) => patch('branding', { ...r.branding, preferredStoreDisplayName: e.target.value })} /></label><label className="text-sm text-slate-300">Geographic suffix<input className={inputClass} value={r.branding.geographicSuffix} onChange={(e) => patch('branding', { ...r.branding, geographicSuffix: e.target.value })} /></label><Check label="Include brand" checked={r.branding.includeBrand} onChange={(v) => patch('branding', { ...r.branding, includeBrand: v })} /><Check label="Keep Brand and Vendor separate" checked={r.branding.separateBrandAndVendor} onChange={() => {}} disabled /></Panel>
      <Panel title="Image SEO"><label className="text-sm text-slate-300">Existing alt-text policy<select className={inputClass} value={r.imageSeo.existingAltTextPolicy} onChange={(e) => patch('imageSeo', { ...r.imageSeo, existingAltTextPolicy: e.target.value as SeoRules['imageSeo']['existingAltTextPolicy'] })}>{['PRESERVE','SUGGEST_IF_WEAK','REPLACE_WITH_CONFIRMATION'].map(v => <option key={v}>{v}</option>)}</select></label><Check label="Prepare alt-text preferences" checked={r.imageSeo.generateAltText} onChange={(v) => patch('imageSeo', { ...r.imageSeo, generateAltText: v })} /><Check label="Avoid decorative language" checked={r.imageSeo.avoidDecorativeLanguage} onChange={() => {}} disabled /></Panel>
      <Panel title="Structured Data"><label className="text-sm text-slate-300">Existing output policy<select className={inputClass} value={r.structuredData.outputPolicy} onChange={(e) => patch('structuredData', { ...r.structuredData, outputPolicy: e.target.value as SeoRules['structuredData']['outputPolicy'] })}><option>TRUST_EXISTING</option><option>REQUEST_INSPECTION</option></select></label><Check label="Validate product data later" checked={r.structuredData.validateProduct} onChange={(v) => patch('structuredData', { ...r.structuredData, validateProduct: v })} /><Check label="Never invent identifiers" checked={r.structuredData.neverInventIdentifiers} onChange={() => {}} disabled /><Check label="No structured-data injection" checked={!r.structuredData.injectStructuredData} onChange={() => {}} disabled /></Panel>
      <Panel title="Indexing Safety"><Check label="Publish as indexable by default" checked={r.indexing.publishIndexableByDefault} onChange={(v) => patch('indexing', { ...r.indexing, publishIndexableByDefault: v })} /><Check label="Respect seo.hidden" checked={r.indexing.respectSeoHidden} onChange={() => {}} disabled /><Check label="Never apply noindex automatically" checked={r.indexing.neverAutoNoindex} onChange={() => {}} disabled /><Check label="Confirm future noindex changes" checked={r.indexing.requireConfirmationForNoindex} onChange={() => {}} disabled /></Panel>
      <Panel title="SEO Quality Rules"><label className="text-sm text-slate-300">Default severity<select className={inputClass} value={r.quality.defaultSeverity} onChange={(e) => patch('quality', { ...r.quality, defaultSeverity: e.target.value as SeoRules['quality']['defaultSeverity'] })}>{['INFO','WARNING','BLOCKING'].map(v => <option key={v}>{v}</option>)}</select></label><Check label="Require verified claims" checked={r.quality.requireVerifiedClaims} onChange={() => {}} disabled /><Check label="Detect duplicate handles" checked={r.quality.detectDuplicateHandles} onChange={(v) => patch('quality', { ...r.quality, detectDuplicateHandles: v })} /><Check label="Detect Brand/Vendor confusion" checked={r.quality.detectBrandVendorConfusion} onChange={(v) => patch('quality', { ...r.quality, detectBrandVendorConfusion: v })} /></Panel>
    </div> : null}
    {error ? <p className="mt-4 text-sm text-rose-300" role="alert">{error}</p> : null}
    {editorVisible ? <div className="mt-7 flex justify-end"><button type="button" disabled={!selected || saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-45">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save SEO Profile</button></div> : null}
    <p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-3.5 w-3.5" />No Shopify SEO, URL, theme, structured-data, or indexing changes are made.</p>
    </fieldset>
  </div>;
}
